import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WrapperProvider from "@/providers/wrappedProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WrapperProvider>{children}</WrapperProvider>
      </body>
    </html>
  );
}
